
package bookclient;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookServiceInterface", targetNamespace = "http://applicationservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookServiceInterface {


    /**
     * 
     * @return
     *     returns java.util.List<bookclient.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBooks", targetNamespace = "http://applicationservice.com/", className = "bookclient.GetAllBooks")
    @ResponseWrapper(localName = "getAllBooksResponse", targetNamespace = "http://applicationservice.com/", className = "bookclient.GetAllBooksResponse")
    @Action(input = "http://applicationservice.com/BookServiceInterface/getAllBooksRequest", output = "http://applicationservice.com/BookServiceInterface/getAllBooksResponse")
    public List<Book> getAllBooks();

}
