
package bookclient;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookServiceInterface", targetNamespace = "http://applicationservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookServiceInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addBook", targetNamespace = "http://applicationservice.com/", className = "bookclient.AddBook")
    @ResponseWrapper(localName = "addBookResponse", targetNamespace = "http://applicationservice.com/", className = "bookclient.AddBookResponse")
    @Action(input = "http://applicationservice.com/BookServiceInterface/addBookRequest", output = "http://applicationservice.com/BookServiceInterface/addBookResponse")
    public String addBook(
        @WebParam(name = "arg0", targetNamespace = "")
        Book arg0);

    /**
     * 
     * @return
     *     returns java.util.List<bookclient.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBooks", targetNamespace = "http://applicationservice.com/", className = "bookclient.GetAllBooks")
    @ResponseWrapper(localName = "getAllBooksResponse", targetNamespace = "http://applicationservice.com/", className = "bookclient.GetAllBooksResponse")
    @Action(input = "http://applicationservice.com/BookServiceInterface/getAllBooksRequest", output = "http://applicationservice.com/BookServiceInterface/getAllBooksResponse")
    public List<Book> getAllBooks();

    /**
     * 
     * @param bookId
     * @return
     *     returns bookclient.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookById", targetNamespace = "http://applicationservice.com/", className = "bookclient.GetBookById")
    @ResponseWrapper(localName = "getBookByIdResponse", targetNamespace = "http://applicationservice.com/", className = "bookclient.GetBookByIdResponse")
    @Action(input = "http://applicationservice.com/BookServiceInterface/getBookByIdRequest", output = "http://applicationservice.com/BookServiceInterface/getBookByIdResponse")
    public Book getBookById(
        @WebParam(name = "book_id", targetNamespace = "")
        String bookId);

}
